model: 'TrajGAT'
data: 'porto_20inf'
dis_type: 'dtw'
length: 'long'
optimizer: 'Adam'
init_lr: 0.00002


max_nodes: 50
max_depth: 50
sample_num: 20
alpha: 16
train_data_range: [0, 7000]
val_data_range: [7000, 8000]
test_data_range: [8000, 10000]
num_workers: 8 # was 8

train_batch_size: 2
eval_batch_size: 200
matrix_cal_batch: 100
epoch: 0 # was 100


d_input: 4
d_model: 128
num_head: 8
num_encoder_layers: 3
encoder_dropout: 0.01
in_feat_dropout: 0.0
d_lap_pos: 8

batch_norm: True
layer_norm: False
use_bias: False


weight_decay: 0.0
lr_reduce_factor: 0.5
lr_schedule_patience: 5

# traj_path: 'data/porto_20200_TrajGAT_trajsimi_hausdorff_traj.pkl'
# dis_matrix_path: 'data/porto_20200_TrajGAT_trajsimi_hausdorff_simi.pkl'


model_best_wts_path: 'model/wts/{}_{}_{}_{}_wts_hr10 {:.4f}.pkl'


# data_features: [-8.616178175552571, 0.05779256281472269, 41.1594322983062, 0.07500122113317888]
# x_range: [-15.630759, -3.930948]
# y_range: [36.886104, 45.657225]
data_features: [-959451.5110142411, 2871.9479509546736, 5035655.751517582, 1939.0055971372537]
x_range: [-968535.007007895, -948355.2323558722]
y_range: [5027117.916994769, 5043158.53248387]
