model: 'TrajGAT'
data: 'geolife_all_20inf'
dis_type: 'dtw'
length: 'long'
optimizer: 'Adam'
init_lr: 0.00002


max_nodes: 50
max_depth: 40
sample_num: 20
alpha: 16
train_data_range: [0, 7000]
val_data_range: [7000, 8000]
test_data_range: [8000, 10000]
num_workers: 8 # was 8

train_batch_size: 2
eval_batch_size: 200
matrix_cal_batch: 100
epoch: 0 # was 100


d_input: 4
d_model: 128
num_head: 8
num_encoder_layers: 3
encoder_dropout: 0.01
in_feat_dropout: 0.0
d_lap_pos: 8

batch_norm: True
layer_norm: False
use_bias: False


weight_decay: 0.0
lr_reduce_factor: 0.5
lr_schedule_patience: 5




# traj_path: 'data/porto_20200_TrajGAT_trajsimi_hausdorff_traj.pkl'
# dis_matrix_path: 'data/porto_20200_TrajGAT_trajsimi_hausdorff_simi.pkl'


model_best_wts_path: 'model/wts/{}_{}_{}_{}_wts_hr10 {:.4f}.pkl'


data_features: [12953578.474185357, 11483.55763947434, 4863505.103274707, 11335.601638975157]
x_range: [12848365, 13080942]
y_range: [4785126, 5021110]
# x_range: [12848366.496750318, 13080941.74476558]
# y_range: [4785127.712059225, 5021109.611969228]